### ISSUE TITLE
promises-aplus-tests   验证通过不了哦

### ISSUE THREAD

**Issue by ben-Run** [yizhengfeng-jj/promise#1]
![image](https://user-images.githubusercontent.com/17672822/93453822-bc29c800-f90c-11ea-8ee4-936ca551fc4d.png)

**Comment by yizhengfeng-jj** [comment]
你好，我把我的代码又跑了一遍，没问题呀
![image](https://user-images.githubusercontent.com/20452750/93456269-03fe1e80-f910-11ea-955e-7814334d42a9.png)
你是用的promises-aplus-tests么
![image](https://user-images.githubusercontent.com/20452750/93456319-1a0bdf00-f910-11ea-9527-d7ff2e504ace.png)

你那个错是因为你把最后一个入口屏蔽了
![image](https://user-images.githubusercontent.com/20452750/93456438-47f12380-f910-11ea-8195-1d67f56b4ebd.png)

我刚刚让我同事克隆了，完整的跑了一遍的，也没问题，你在检查下，再给我说一下哈

**Comment by ben-Run** [comment]
在cmd 下可以了

**Comment by yizhengfeng-jj** [comment]
> 在cmd 下可以了

好的 那我关了这个issue了哈
